# Generated by Django 3.2 on 2023-03-07 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20230307_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules',
            name='blockBoxModule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.blockboxmodule'),
        ),
        migrations.AddField(
            model_name='modules',
            name='drawBoxModule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.drawboxmodule'),
        ),
        migrations.AddField(
            model_name='modules',
            name='laserModule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.lasermodule'),
        ),
        migrations.AddField(
            model_name='modules',
            name='polarizedScreenModule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.polarizedscreenmodule'),
        ),
        migrations.AddField(
            model_name='modules',
            name='portalGunModule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.portalgunmodule'),
        ),
        migrations.AddField(
            model_name='modules',
            name='voiceFilterinModule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.voicefilterinmodule'),
        ),
        migrations.AlterField(
            model_name='modules',
            name='bombModule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.bombmodule'),
        ),
    ]
