# Generated by Django 3.2 on 2023-03-07 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20230307_1827'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VoiceFilterinModule',
            new_name='VoiceFilteringModule',
        ),
    ]
