# Generated by Django 3.2 on 2023-03-07 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_voicefilterinmodule_voicefilteringmodule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Modules',
        ),
    ]
