# Generated by Django 3.2 on 2023-03-07 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_delete_modules'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='timeBlockBoxModule',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='timeBombModule',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='timeDrawBoxModule',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='timeLaserModule',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='timePolarizedScreenModule',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='timePortalGunModule',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='timeVoiceFilteringModule',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
