# Generated by Django 3.2 on 2023-03-07 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20230307_1836'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(blank=True, default=False, null=True)),
                ('hint', models.ManyToManyField(blank=True, null=True, to='api.Hints')),
            ],
        ),
        migrations.DeleteModel(
            name='BlockBoxModule',
        ),
        migrations.DeleteModel(
            name='BombModule',
        ),
        migrations.DeleteModel(
            name='DrawBoxModule',
        ),
        migrations.DeleteModel(
            name='LaserModule',
        ),
        migrations.DeleteModel(
            name='PolarizedScreenModule',
        ),
        migrations.DeleteModel(
            name='PortalGunModule',
        ),
        migrations.DeleteModel(
            name='VoiceFilteringModule',
        ),
    ]
