# Generated by Django 3.2 on 2023-03-07 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20230307_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='teams',
            options={},
        ),
        migrations.RemoveField(
            model_name='teams',
            name='startedAt',
        ),
        migrations.RemoveField(
            model_name='teams',
            name='teamsize',
        ),
        migrations.RemoveField(
            model_name='teams',
            name='timeBlockBoxModule',
        ),
        migrations.RemoveField(
            model_name='teams',
            name='timeBombModule',
        ),
        migrations.RemoveField(
            model_name='teams',
            name='timeDrawBoxModule',
        ),
        migrations.RemoveField(
            model_name='teams',
            name='timeLaserModule',
        ),
        migrations.RemoveField(
            model_name='teams',
            name='timePolarizedScreenModule',
        ),
        migrations.RemoveField(
            model_name='teams',
            name='timePortalGunModule',
        ),
        migrations.RemoveField(
            model_name='teams',
            name='timeVoiceFilteringModule',
        ),
        migrations.RemoveField(
            model_name='teams',
            name='time_spent',
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_spent', models.IntegerField(blank=True, null=True)),
                ('startedAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('timeBombModule', models.IntegerField(blank=True, null=True)),
                ('timeLaserModule', models.IntegerField(blank=True, null=True)),
                ('timePortalGunModule', models.IntegerField(blank=True, null=True)),
                ('timeDrawBoxModule', models.IntegerField(blank=True, null=True)),
                ('timeBlockBoxModule', models.IntegerField(blank=True, null=True)),
                ('timeVoiceFilteringModule', models.IntegerField(blank=True, null=True)),
                ('timePolarizedScreenModule', models.IntegerField(blank=True, null=True)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.teams')),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
                'ordering': ['startedAt'],
            },
        ),
        migrations.AddField(
            model_name='teams',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, to='api.Members'),
        ),
    ]
