# Generated by Django 3.2 on 2023-03-13 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20230307_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='DummyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('randomNumber', models.IntegerField(blank=True, default=0, null=True)),
                ('randomBoolean', models.BooleanField(blank=True, default=False, null=True)),
                ('randomString', models.CharField(blank=True, default='dummy', max_length=100, null=True)),
            ],
        ),
    ]
