# Generated by Django 3.2 on 2023-03-14 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_dummymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules',
            name='keypadCode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
