# Generated by Django 4.1.3 on 2023-04-11 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_modules_keypadcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimerModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTimer', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
